# https://github.com/arangodb/arangodb-docker/issues/22

# Specify the starting point image from docker-hub.  In this case its a docker image with node.js preinstalled on alpine linux.
FROM postgres:latest

CMD postgres