version: '3.1'

services:
  db-influxdb-mro:
    image: influxdb
    container_name: db-influxdb-mro
    restart: always
    ports:
      - 8086:8086
    env_file: 
      - influxdb.env
    volumes:
      - influxdb-mro-vol:/var/lib/influxdb

volumes:
  influxdb-mro-vol:
    driver: local

