version: '3.1'

services:
  server-mqtt:
    image: rabbitmq-mro
    # image: rabbitmq:management
    container_name: server-rabbitmq-mro
    hostname: robo-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8882:8882"
      - "8883:8883"
      - "15675:15675"
    env_file: 
      - rabbitmq.env
    # command: 
    #   - rabbitmq-plugins enable rabbitmq_management
    #   - rabbitmq-plugins enable rabbitmq_mqtt
    #   - rabbitmq-plugins enable rabbitmq_web_mqtt
    networks:
      - webnet

networks:
  webnet:
      driver: bridge
